server:
  port: 8084

spring:
  application:
    name: @application.name@
  config:
    import:
      - classpath:base.yml
      - classpath:datasource.yml
      - classpath:rpc.yml
      - classpath:cache.yml
