server:
  port: 8003

spring:
  application:
    name: @application.name@
  ai:
#    dashscope:
#      api-key: ${chatApikey}
    openai:
      base-url: https://api.chatanywhere.tech
      api-key: ${embeddingApikey}

logging:
  level:
    root: info

# 向量数据库配置
vector-datasource:
  baseUrl: http://117.72.194.214:8000
  tenantName: knowgo
  databaseName: knowgo
  collectionName: knowgo