server:
  port: 9001

spring:
  application:
    name: @application.name@
  #saa配置
  ai:
    dashscope:
      api-key: ${Qwen.apiKey}
    vectorstore:
      type: chroma
      chroma:
        client:
          host: http://192.168.1.14
          port: 8000
        tenant-name: knowgo
        database-name: knowgo
        collection-name: knowgo
        initialize-schema: true
