spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${com.fw.know.go.nacos.server.url}
        namespace: ${com.fw.know.go.dubbo.nacos.namespace}
        group: ${com.fw.know.go.dubbo.nacos.group}
      config:
        server-addr: ${com.fw.know.go.nacos.server.url}
        namespace: ${com.fw.know.go.dubbo.nacos.namespace}
        group: ${com.fw.know.go.dubbo.nacos.group}
        file-extension: properties
        name: ${spring.application.name}