spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${com.fw.know.go.nacos.server.url}
      config:
        server-addr: ${com.fw.know.go.nacos.server.url}
        file-extension: properties
        name: ${spring.application.name}