spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${com.fw.know.go.nacos.server.url}
        # 禁用SpringCloud服务注册发现
        enabled: false
      config:
        server-addr: ${com.fw.know.go.nacos.server.url}
        file-extension: properties
        name: ${spring.application.name}