server:
  port: 8003

spring:
  application:
    name: @application.name@

logging:
  level:
    root: info

# 向量数据库配置
vector-datasource:
  baseUrl: http://117.72.194.214:8000
  tenantName: knowgo
  databaseName: knowgo
  collectionName: knowgo

# Ai 配置
know:
  go:
    ai:
      chat-api-key: ${chatApikey}
      embedding-api-key: ${embeddingApikey}